#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🕵️‍♂️ Checking your crappy code 🕵️‍♂️'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ dead-code:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn dead-code:check || echo '🤢🤮🤢 dead-code:check failed 🤢🤮🤢'
echo '✅✅✅ dead-code:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ lint:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn lint:check || echo '🤢🤮🤢 lint:check failed 🤢🤮🤢'
echo '✅✅✅ lint:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ types:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn types:check || echo '🤢🤮🤢 types:check failed 🤢🤮🤢'
echo '✅✅✅ types:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ format:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn format:check || echo '🤢🤮🤢 format:check failed 🤢🤮🤢'
echo '✅✅✅ format:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ test:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn test:check || echo '🤢🤮🤢 test:check failed 🤢🤮🤢'
echo '✅✅✅ test:check ✅✅✅'

echo '🤔🤔🤔 Alright... code looks fine to me... trying to build now. 🤔🤔🤔'
yarn build || echo '🤢🤮🤢 build failed 🤢🤮🤢'
echo '✅✅✅ You win this time... I am committing this now. ✅✅✅'