#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🕵️‍♂️ Checking your crappy code 🕵️‍♂️'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ clean 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn clean || (echo '🤢🤮🤢 clean failed 🤢🤮🤢'; false)
echo '✅✅✅ clean ✅✅✅'


echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ deadCode:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn deadCode:check || (echo '🤢🤮🤢 deadCode:check failed 🤢🤮🤢'; false)
echo '✅✅✅ deadCode:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ lint:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn lint:check || (echo '🤢🤮🤢 lint:check failed 🤢🤮🤢'; false);
echo '✅✅✅ lint:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ types:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn types:check || (echo '🤢🤮🤢 types:check failed 🤢🤮🤢'; false)
echo '✅✅✅ types:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ format:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn format:check || (echo '🤢🤮🤢 format:check failed 🤢🤮🤢'; false)
echo '✅✅✅ format:check ✅✅✅'

echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ test:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
yarn test:check || (echo '🤢🤮🤢 test:check failed 🤢🤮🤢'; false)
echo '✅✅✅ test:check ✅✅✅'

echo '🤔🤔🤔 Alright... code looks fine to me... trying to build now. 🤔🤔🤔'
yarn build || (echo '🤢🤮🤢 build failed 🤢🤮🤢'; false)
echo '✅✅✅ You win this time... I am committing this now. ✅✅✅'