name: Build and test

on: [push]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.4.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm run install

      - name: deadCode:check
        run: npm run deadCode:check

      - name: lint:check
        run: npm run lint:check

      - name: types:check
        run: npm run types:check

      - name: format:check
        run: npm run format:check

      - name: test:check
        run: npm run test:check

      - name: build
        run: npm run build
