name: Check code

on: [push]

jobs:
    test:
        name: Check code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: yarn --non-interactive --frozen-lockfile --ignore-scripts

            - name: deadCode:check
              run: yarn deadCode:check

            - name: lint:check
              run: yarn lint:check

            - name: types:check
              run: yarn types:check

            - name: format:check
              run: yarn format:check

            - name: test:check
              run: yarn test:check

            - name: build
              run: yarn build
