name: Run tests

on: [pull_request, push]

jobs:
    test:
        name: Run tests & display coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: yarn --non-interactive --frozen-lockfile --ignore-scripts

            - name: Run tests
              run: yarn test
